
window.addEventListener('load',()=>setTimeout(()=>document.querySelector('.loader')?.classList.add('hide'),650));
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const cursor=$('.cursor');window.addEventListener('mousemove',e=>{if(cursor){cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'}});$$('a,button,.card,input,textarea,select').forEach(el=>{el.addEventListener('mouseenter',()=>cursor?.classList.add('big'));el.addEventListener('mouseleave',()=>cursor?.classList.remove('big'))});
$$('.hamb').forEach(b=>b.onclick=()=>$('.mobile')?.classList.add('open'));$('.close')?.addEventListener('click',()=>$('.mobile')?.classList.remove('open'));
$$('.card').forEach(c=>{c.addEventListener('mousemove',e=>{let r=c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;c.style.transform=`perspective(1000px) rotateX(${-(y-r.height/2)/24}deg) rotateY(${(x-r.width/2)/24}deg) translateY(-8px)`});c.addEventListener('mouseleave',()=>c.style.transform='')});
const logo=$('.tilt-logo');window.addEventListener('mousemove',e=>{if(logo){let x=(e.clientX/innerWidth-.5)*18,y=(e.clientY/innerHeight-.5)*-12;logo.style.transform=`perspective(900px) rotateY(${x}deg) rotateX(${y}deg)`}});
const ioReveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});$$('.section,.reveal,.card').forEach(x=>ioReveal.observe(x));
const nums=$$('[data-count]');const ioNums=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){let el=e.target,t=+el.dataset.count,n=0,s=Math.max(1,Math.ceil(t/85));let i=setInterval(()=>{n+=s;if(n>=t){n=t;clearInterval(i)}el.textContent=n.toLocaleString()},16);ioNums.unobserve(el)}}));nums.forEach(n=>ioNums.observe(n));
$$('.rule').forEach(r=>r.onclick=()=>r.classList.toggle('open'));const ruleSearch=$('#ruleSearch');if(ruleSearch){ruleSearch.oninput=()=>{$$('.rule').forEach(r=>r.style.display=r.dataset.rule.includes(ruleSearch.value.toLowerCase())||r.textContent.toLowerCase().includes(ruleSearch.value.toLowerCase())?'block':'none')}}
const evs=[{d:3,t:'Staff Q&A',c:'community'},{d:7,t:'Operation Blackout',c:'police'},{d:12,t:'Car Meet',c:'racing'},{d:16,t:'Dockside Conflict',c:'criminal'},{d:21,t:'Midnight Race',c:'racing'},{d:27,t:'EMS Training',c:'community'}];const cal=$('#calendar');function renderCal(filter='all'){if(!cal)return;cal.innerHTML='';for(let i=1;i<=35;i++){let e=evs.find(x=>x.d==i&&(filter=='all'||x.c==filter));let day=document.createElement('div');day.className='day';day.innerHTML=`<b>${i}</b>${e?`<span data-cat="${e.c}" data-title="${e.t}" data-time="Day ${i} • 21:00 UK" data-desc="Discord linked ${e.c} event. Replace the URL with your real Discord event or message link." data-discord="https://discord.com">${e.t}</span>`:''}`;cal.appendChild(day)}}renderCal();$$('.chip').forEach(ch=>ch.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));ch.classList.add('active');renderCal(ch.dataset.filter)});
const modal=$('#eventModal');function openEvent(el){if(!modal)return;$('#mCat').textContent=(el.dataset.cat||'event').toUpperCase();$('#mTitle').textContent=el.dataset.title;$('#mTime').textContent=el.dataset.time;$('#mDesc').textContent=el.dataset.desc;$('#mDiscord').href=el.dataset.discord||'https://discord.com';modal.classList.add('open')}document.addEventListener('click',e=>{let ev=e.target.closest('.event-card,[data-title][data-time]');if(ev)openEvent(ev);if(e.target.classList.contains('modal-close')||e.target===modal)modal?.classList.remove('open')});
const form=$('#suggestForm'),list=$('#suggestionsList');let suggestions=JSON.parse(localStorage.getItem('ids_suggestions')||'null')||[{title:'Add more city events',cat:'General',body:'Weekly staff-led arcs with rewards.',votes:42,status:'In review'},{title:'Import classic police cars',cat:'Vehicles',body:'More black and white emergency vehicles.',votes:31,status:'Pending'},{title:'Business ownership system',cat:'Jobs',body:'Allow players to apply for restaurants and clubs.',votes:24,status:'Accepted'}];function drawSug(){if(!list)return;list.innerHTML=suggestions.map((s,i)=>`<article class="card"><span class="tag">${s.cat} • ${s.status}</span><h3>${s.title}</h3><p>${s.body}</p><div class="vote"><button data-vote="${i}">▲ Vote</button><b>${s.votes}</b></div></article>`).join('')}drawSug();form?.addEventListener('submit',e=>{e.preventDefault();let title=$('#sTitle').value.trim(),body=$('#sBody').value.trim();if(!title||!body)return;suggestions.unshift({title,cat:$('#sCat').value,body,votes:1,status:'Pending'});localStorage.setItem('ids_suggestions',JSON.stringify(suggestions));form.reset();drawSug()});document.addEventListener('click',e=>{if(e.target.dataset.vote){suggestions[e.target.dataset.vote].votes++;localStorage.setItem('ids_suggestions',JSON.stringify(suggestions));drawSug()}});
const canvas=$('#bg3d');if(canvas){const ctx=canvas.getContext('2d');let w,h,pts=[];function resize(){w=canvas.width=innerWidth;h=canvas.height=innerHeight;pts=Array.from({length:Math.min(130,Math.floor(w/12))},()=>({x:Math.random()*w,y:Math.random()*h,z:Math.random()*2+0.4,vx:(Math.random()-.5)*.18,vy:(Math.random()-.5)*.18}))}resize();addEventListener('resize',resize);function loop(){ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(255,255,255,.72)';ctx.strokeStyle='rgba(255,255,255,.15)';pts.forEach((a,i)=>{a.x+=a.vx*a.z;a.y+=a.vy*a.z;if(a.x<0||a.x>w)a.vx*=-1;if(a.y<0||a.y>h)a.vy*=-1;ctx.beginPath();ctx.arc(a.x,a.y,a.z,0,Math.PI*2);ctx.fill();for(let j=i+1;j<pts.length;j++){let b=pts[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<135){ctx.globalAlpha=(135-d)/900;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.globalAlpha=1}}});requestAnimationFrame(loop)}loop()}

document.querySelectorAll('.card').forEach(card=>{
 card.addEventListener('mousemove',e=>{
  const r=card.getBoundingClientRect();
  const x=e.clientX-r.left;
  const y=e.clientY-r.top;
  card.style.setProperty('--mx',x+'px');
  card.style.setProperty('--my',y+'px');
 });
});
